import { PrismaClient } from '@prisma/client'
import argon2 from 'argon2'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // ─── Admin User ────────────────────────────────────────────────────────────
  const adminHash = await argon2.hash('Admin123!')
  const admin = await prisma.user.upsert({
    where: { email: 'admin@pcforge.dev' },
    update: {},
    create: {
      email: 'admin@pcforge.dev',
      name: 'PCForge Admin',
      passwordHash: adminHash,
      role: 'ADMIN',
      isVerified: true,
    },
  })

  const customerHash = await argon2.hash('Customer123!')
  await prisma.user.upsert({
    where: { email: 'juan@example.com' },
    update: {},
    create: {
      email: 'juan@example.com',
      name: 'Juan García',
      passwordHash: customerHash,
      role: 'CUSTOMER',
      isVerified: true,
      addresses: {
        create: {
          name: 'Casa',
          street: 'Cra 7 #32-16',
          city: 'Bogotá',
          state: 'Cundinamarca',
          country: 'CO',
          postalCode: '110231',
          isDefault: true,
        },
      },
    },
  })

  // ─── Products ──────────────────────────────────────────────────────────────
  const products = [
    // CPUs
    {
      name: 'Intel Core i9-14900K',
      slug: 'intel-core-i9-14900k',
      brand: 'Intel',
      category: 'CPU' as const,
      description: 'The flagship Intel desktop processor. 24 cores (8P+16E), up to 6.0 GHz boost, with integrated UHD 770 graphics. Best for gaming and content creation.',
      price: 589.99,
      stock: 42,
      images: ['https://cdn.pcforge.dev/products/i9-14900k.jpg'],
      tdp: 253,
      socket: 'LGA1700',
      isFeatured: true,
      specs: [
        { key: 'Cores', value: '24 (8P+16E)' },
        { key: 'Threads', value: '32' },
        { key: 'Base Clock', value: '3.2', unit: 'GHz' },
        { key: 'Boost Clock', value: '6.0', unit: 'GHz' },
        { key: 'TDP', value: '253', unit: 'W' },
        { key: 'Socket', value: 'LGA1700' },
        { key: 'Memory Support', value: 'DDR4/DDR5' },
        { key: 'PCIe Version', value: '5.0' },
        { key: 'L3 Cache', value: '36', unit: 'MB' },
        { key: 'Process Node', value: 'Intel 7 (10nm)' },
      ],
    },
    {
      name: 'AMD Ryzen 9 7950X',
      slug: 'amd-ryzen-9-7950x',
      brand: 'AMD',
      category: 'CPU' as const,
      description: '16-core powerhouse for content creators and professionals. AM5 platform with DDR5 and PCIe 5.0. Best multi-threaded performance in its class.',
      price: 549.99,
      stock: 35,
      images: ['https://cdn.pcforge.dev/products/r9-7950x.jpg'],
      tdp: 170,
      socket: 'AM5',
      memoryType: 'DDR5',
      isFeatured: true,
      specs: [
        { key: 'Cores', value: '16' },
        { key: 'Threads', value: '32' },
        { key: 'Base Clock', value: '4.5', unit: 'GHz' },
        { key: 'Boost Clock', value: '5.7', unit: 'GHz' },
        { key: 'TDP', value: '170', unit: 'W' },
        { key: 'Socket', value: 'AM5' },
        { key: 'Memory Support', value: 'DDR5 only' },
        { key: 'PCIe Version', value: '5.0' },
        { key: 'L3 Cache', value: '64', unit: 'MB' },
        { key: 'Process Node', value: 'TSMC 5nm' },
      ],
    },
    {
      name: 'Intel Core i5-14600K',
      slug: 'intel-core-i5-14600k',
      brand: 'Intel',
      category: 'CPU' as const,
      description: 'Best price-to-performance CPU for gaming. 14 cores, up to 5.3 GHz, ideal for 1080p and 1440p gaming builds.',
      price: 299.99,
      stock: 78,
      images: ['https://cdn.pcforge.dev/products/i5-14600k.jpg'],
      tdp: 181,
      socket: 'LGA1700',
      specs: [
        { key: 'Cores', value: '14 (6P+8E)' },
        { key: 'Threads', value: '20' },
        { key: 'Base Clock', value: '3.5', unit: 'GHz' },
        { key: 'Boost Clock', value: '5.3', unit: 'GHz' },
        { key: 'TDP', value: '181', unit: 'W' },
        { key: 'Socket', value: 'LGA1700' },
        { key: 'Memory Support', value: 'DDR4/DDR5' },
        { key: 'L3 Cache', value: '24', unit: 'MB' },
      ],
    },
    {
      name: 'AMD Ryzen 5 7600X',
      slug: 'amd-ryzen-5-7600x',
      brand: 'AMD',
      category: 'CPU' as const,
      description: 'Affordable AM5 entry point. 6 cores of Zen 4 performance. Great for gaming and everyday tasks.',
      price: 229.99,
      stock: 95,
      images: ['https://cdn.pcforge.dev/products/r5-7600x.jpg'],
      tdp: 105,
      socket: 'AM5',
      memoryType: 'DDR5',
      specs: [
        { key: 'Cores', value: '6' },
        { key: 'Threads', value: '12' },
        { key: 'Boost Clock', value: '5.3', unit: 'GHz' },
        { key: 'TDP', value: '105', unit: 'W' },
        { key: 'Socket', value: 'AM5' },
        { key: 'Memory Support', value: 'DDR5 only' },
      ],
    },
    // GPUs
    {
      name: 'NVIDIA GeForce RTX 4090',
      slug: 'nvidia-geforce-rtx-4090',
      brand: 'NVIDIA',
      category: 'GPU' as const,
      description: 'The fastest consumer GPU ever made. 24GB GDDR6X, Ada Lovelace architecture, DLSS 3 with Frame Generation. Dominates 4K gaming and AI workloads.',
      price: 1599.99,
      stock: 12,
      images: ['https://cdn.pcforge.dev/products/rtx-4090.jpg'],
      tdp: 450,
      isFeatured: true,
      specs: [
        { key: 'VRAM', value: '24', unit: 'GB GDDR6X' },
        { key: 'CUDA Cores', value: '16384' },
        { key: 'Boost Clock', value: '2.52', unit: 'GHz' },
        { key: 'Memory Bandwidth', value: '1008', unit: 'GB/s' },
        { key: 'TDP', value: '450', unit: 'W' },
        { key: 'PCIe', value: '4.0 x16' },
        { key: 'Display Outputs', value: '1x HDMI 2.1, 3x DP 1.4a' },
        { key: 'Architecture', value: 'Ada Lovelace' },
      ],
    },
    {
      name: 'NVIDIA GeForce RTX 4070 Ti Super',
      slug: 'nvidia-geforce-rtx-4070-ti-super',
      brand: 'NVIDIA',
      category: 'GPU' as const,
      description: '16GB GDDR6X, excellent 1440p and solid 4K performance. Great value in the high-end segment with DLSS 3.',
      price: 799.99,
      stock: 28,
      images: ['https://cdn.pcforge.dev/products/rtx-4070-ti-super.jpg'],
      tdp: 285,
      isFeatured: true,
      specs: [
        { key: 'VRAM', value: '16', unit: 'GB GDDR6X' },
        { key: 'CUDA Cores', value: '8448' },
        { key: 'Boost Clock', value: '2.61', unit: 'GHz' },
        { key: 'TDP', value: '285', unit: 'W' },
        { key: 'PCIe', value: '4.0 x16' },
      ],
    },
    {
      name: 'AMD Radeon RX 7900 XTX',
      slug: 'amd-radeon-rx-7900-xtx',
      brand: 'AMD',
      category: 'GPU' as const,
      description: '24GB GDDR6, RDNA 3 architecture. AMD flagship competing directly with RTX 4080. Excellent open-source driver support on Linux.',
      price: 849.99,
      stock: 22,
      images: ['https://cdn.pcforge.dev/products/rx-7900-xtx.jpg'],
      tdp: 355,
      specs: [
        { key: 'VRAM', value: '24', unit: 'GB GDDR6' },
        { key: 'Stream Processors', value: '6144' },
        { key: 'Boost Clock', value: '2.5', unit: 'GHz' },
        { key: 'Memory Bandwidth', value: '960', unit: 'GB/s' },
        { key: 'TDP', value: '355', unit: 'W' },
        { key: 'Architecture', value: 'RDNA 3' },
      ],
    },
    {
      name: 'NVIDIA GeForce RTX 4060',
      slug: 'nvidia-geforce-rtx-4060',
      brand: 'NVIDIA',
      category: 'GPU' as const,
      description: 'Best 1080p gaming GPU at this price point. 8GB GDDR6, DLSS 3, very power efficient at only 115W TDP.',
      price: 299.99,
      stock: 65,
      images: ['https://cdn.pcforge.dev/products/rtx-4060.jpg'],
      tdp: 115,
      specs: [
        { key: 'VRAM', value: '8', unit: 'GB GDDR6' },
        { key: 'CUDA Cores', value: '3072' },
        { key: 'Boost Clock', value: '2.46', unit: 'GHz' },
        { key: 'TDP', value: '115', unit: 'W' },
        { key: 'PCIe', value: '4.0 x8' },
      ],
    },
    // Motherboards
    {
      name: 'ASUS ROG STRIX Z790-E Gaming WiFi',
      slug: 'asus-rog-strix-z790-e-gaming-wifi',
      brand: 'ASUS',
      category: 'MOTHERBOARD' as const,
      description: 'Premium Z790 ATX motherboard for LGA1700. Supports DDR5, PCIe 5.0 for GPU and NVMe. 18+1 power stages, WiFi 6E, 2.5Gb LAN.',
      price: 449.99,
      stock: 30,
      images: ['https://cdn.pcforge.dev/products/z790-e.jpg'],
      socket: 'LGA1700',
      formFactor: 'ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'Intel Z790' },
        { key: 'Socket', value: 'LGA1700' },
        { key: 'Memory Type', value: 'DDR5' },
        { key: 'Memory Slots', value: '4 (up to 128GB)' },
        { key: 'Max Memory Speed', value: 'DDR5-7800+' },
        { key: 'PCIe x16 Slots', value: '2 (PCIe 5.0 + PCIe 4.0)' },
        { key: 'M.2 Slots', value: '5 (PCIe 5.0 x4 + PCIe 4.0 x4)' },
        { key: 'USB Ports', value: 'USB 3.2 Gen 2x2, Thunderbolt 4' },
        { key: 'WiFi', value: 'WiFi 6E (802.11ax)' },
        { key: 'LAN', value: '2.5 Gigabit' },
        { key: 'Form Factor', value: 'ATX' },
      ],
    },
    {
      name: 'MSI MAG X670E Tomahawk WiFi',
      slug: 'msi-mag-x670e-tomahawk-wifi',
      brand: 'MSI',
      category: 'MOTHERBOARD' as const,
      description: 'Excellent AM5 mid-range board. X670E with PCIe 5.0 M.2 and GPU slots. DDR5 support, WiFi 6E, 14+2+1 power stages.',
      price: 369.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/x670e-tomahawk.jpg'],
      socket: 'AM5',
      formFactor: 'ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'AMD X670E' },
        { key: 'Socket', value: 'AM5' },
        { key: 'Memory Type', value: 'DDR5' },
        { key: 'Memory Slots', value: '4 (up to 128GB)' },
        { key: 'Max Memory Speed', value: 'DDR5-7800+' },
        { key: 'PCIe x16 Slots', value: '1 (PCIe 5.0)' },
        { key: 'M.2 Slots', value: '4 (1x PCIe 5.0)' },
        { key: 'WiFi', value: 'WiFi 6E' },
        { key: 'LAN', value: '2.5 Gigabit' },
        { key: 'Form Factor', value: 'ATX' },
      ],
    },
    {
      name: 'Gigabyte B760M DS3H DDR4',
      slug: 'gigabyte-b760m-ds3h-ddr4',
      brand: 'Gigabyte',
      category: 'MOTHERBOARD' as const,
      description: 'Budget LGA1700 micro-ATX board. Compatible with DDR4 RAM. Solid B760 chipset for i5/i3 builds. Great entry-level option.',
      price: 129.99,
      stock: 85,
      images: ['https://cdn.pcforge.dev/products/b760m-ds3h.jpg'],
      socket: 'LGA1700',
      formFactor: 'mATX',
      memoryType: 'DDR4',
      specs: [
        { key: 'Chipset', value: 'Intel B760' },
        { key: 'Socket', value: 'LGA1700' },
        { key: 'Memory Type', value: 'DDR4' },
        { key: 'Memory Slots', value: '4 (up to 128GB)' },
        { key: 'M.2 Slots', value: '2' },
        { key: 'Form Factor', value: 'mATX' },
      ],
    },
    // RAM
    {
      name: 'G.Skill Trident Z5 RGB 32GB',
      slug: 'gskill-trident-z5-rgb-32gb-ddr5-6000',
      brand: 'G.Skill',
      category: 'RAM' as const,
      description: 'Premium DDR5-6000 kit. 2x16GB CL36. Optimized for Intel and AMD platforms. Stunning RGB lighting with G.Skill Lighting Control.',
      price: 129.99,
      stock: 60,
      images: ['https://cdn.pcforge.dev/products/trident-z5.jpg'],
      memoryType: 'DDR5',
      specs: [
        { key: 'Type', value: 'DDR5' },
        { key: 'Capacity', value: '32GB (2x16GB)' },
        { key: 'Speed', value: '6000', unit: 'MHz' },
        { key: 'Latency', value: 'CL36-36-36-96' },
        { key: 'Voltage', value: '1.35', unit: 'V' },
        { key: 'RGB', value: 'Yes' },
        { key: 'XMP/EXPO', value: 'XMP 3.0 / EXPO' },
      ],
    },
    {
      name: 'Corsair Vengeance 32GB DDR4',
      slug: 'corsair-vengeance-32gb-ddr4-3600',
      brand: 'Corsair',
      category: 'RAM' as const,
      description: 'Reliable DDR4 kit for LGA1700 and AM4 builds. 2x16GB at 3600MHz CL18. Wide compatibility, proven stability.',
      price: 79.99,
      stock: 110,
      images: ['https://cdn.pcforge.dev/products/vengeance-ddr4.jpg'],
      memoryType: 'DDR4',
      specs: [
        { key: 'Type', value: 'DDR4' },
        { key: 'Capacity', value: '32GB (2x16GB)' },
        { key: 'Speed', value: '3600', unit: 'MHz' },
        { key: 'Latency', value: 'CL18' },
        { key: 'Voltage', value: '1.35', unit: 'V' },
        { key: 'XMP', value: 'XMP 2.0' },
      ],
    },
    {
      name: 'Kingston Fury Beast 64GB DDR5',
      slug: 'kingston-fury-beast-64gb-ddr5-5200',
      brand: 'Kingston',
      category: 'RAM' as const,
      description: '64GB DDR5 kit for professional workstations. 2x32GB at 5200MHz. Ideal for video editing, 3D rendering, and VMs.',
      price: 189.99,
      stock: 25,
      images: ['https://cdn.pcforge.dev/products/fury-beast-64.jpg'],
      memoryType: 'DDR5',
      specs: [
        { key: 'Type', value: 'DDR5' },
        { key: 'Capacity', value: '64GB (2x32GB)' },
        { key: 'Speed', value: '5200', unit: 'MHz' },
        { key: 'Latency', value: 'CL40' },
        { key: 'Voltage', value: '1.25', unit: 'V' },
        { key: 'XMP', value: 'XMP 3.0' },
      ],
    },
    // Storage
    {
      name: 'Samsung 990 Pro 2TB NVMe',
      slug: 'samsung-990-pro-2tb',
      brand: 'Samsung',
      category: 'STORAGE' as const,
      description: 'Fastest PCIe 4.0 NVMe SSD. 7450/6900 MB/s sequential. Ideal as OS drive and game storage. 5-year warranty.',
      price: 169.99,
      stock: 90,
      images: ['https://cdn.pcforge.dev/products/990-pro.jpg'],
      specs: [
        { key: 'Interface', value: 'PCIe 4.0 x4 NVMe 2.0' },
        { key: 'Form Factor', value: 'M.2 2280' },
        { key: 'Capacity', value: '2', unit: 'TB' },
        { key: 'Seq. Read', value: '7450', unit: 'MB/s' },
        { key: 'Seq. Write', value: '6900', unit: 'MB/s' },
        { key: 'NAND', value: 'Samsung V-NAND TLC' },
        { key: 'DRAM Cache', value: '2', unit: 'GB' },
        { key: 'Warranty', value: '5 years' },
        { key: 'TBW', value: '1200', unit: 'TB' },
      ],
    },
    {
      name: 'WD Black SN850X 1TB',
      slug: 'wd-black-sn850x-1tb',
      brand: 'Western Digital',
      category: 'STORAGE' as const,
      description: 'PCIe 4.0 NVMe optimized for gaming. 7300/6300 MB/s, with Game Mode 2.0 technology. PS5 compatible.',
      price: 109.99,
      stock: 75,
      images: ['https://cdn.pcforge.dev/products/sn850x.jpg'],
      specs: [
        { key: 'Interface', value: 'PCIe 4.0 x4 NVMe 1.4' },
        { key: 'Form Factor', value: 'M.2 2280' },
        { key: 'Capacity', value: '1', unit: 'TB' },
        { key: 'Seq. Read', value: '7300', unit: 'MB/s' },
        { key: 'Seq. Write', value: '6300', unit: 'MB/s' },
        { key: 'Warranty', value: '5 years' },
      ],
    },
    {
      name: 'Seagate BarraCuda 4TB HDD',
      slug: 'seagate-barracuda-4tb-hdd',
      brand: 'Seagate',
      category: 'STORAGE' as const,
      description: '4TB 3.5" HDD for mass storage. 5400 RPM, 256MB cache. Perfect secondary drive for games, media, and backups.',
      price: 79.99,
      stock: 120,
      images: ['https://cdn.pcforge.dev/products/barracuda-4tb.jpg'],
      specs: [
        { key: 'Interface', value: 'SATA III 6Gb/s' },
        { key: 'Form Factor', value: '3.5"' },
        { key: 'Capacity', value: '4', unit: 'TB' },
        { key: 'RPM', value: '5400' },
        { key: 'Cache', value: '256', unit: 'MB' },
        { key: 'Warranty', value: '2 years' },
      ],
    },
    // PSUs
    {
      name: 'Corsair RM1000x 1000W',
      slug: 'corsair-rm1000x-1000w',
      brand: 'Corsair',
      category: 'PSU' as const,
      description: 'Fully modular 1000W 80+ Gold PSU. Quiet Zero RPM fan mode at low loads. ATX 3.0 compliant with PCIe 5.0 connector. 10-year warranty.',
      price: 199.99,
      stock: 45,
      images: ['https://cdn.pcforge.dev/products/rm1000x.jpg'],
      wattage: 1000,
      specs: [
        { key: 'Wattage', value: '1000', unit: 'W' },
        { key: 'Efficiency', value: '80+ Gold' },
        { key: 'Modularity', value: 'Fully Modular' },
        { key: 'ATX Version', value: 'ATX 3.0' },
        { key: 'PCIe Connector', value: '12VHPWR (600W native)' },
        { key: 'Fan Size', value: '135mm' },
        { key: 'Zero RPM Mode', value: 'Yes' },
        { key: 'Warranty', value: '10 years' },
      ],
    },
    {
      name: 'Seasonic Focus GX-850',
      slug: 'seasonic-focus-gx-850',
      brand: 'Seasonic',
      category: 'PSU' as const,
      description: '850W 80+ Gold fully modular PSU. Hybrid fan control, 10-year warranty. One of the most reliable PSUs on the market.',
      price: 149.99,
      stock: 55,
      images: ['https://cdn.pcforge.dev/products/focus-gx-850.jpg'],
      wattage: 850,
      specs: [
        { key: 'Wattage', value: '850', unit: 'W' },
        { key: 'Efficiency', value: '80+ Gold' },
        { key: 'Modularity', value: 'Fully Modular' },
        { key: 'Fan Size', value: '120mm' },
        { key: 'Hybrid Fan Mode', value: 'Yes' },
        { key: 'Warranty', value: '10 years' },
      ],
    },
    {
      name: 'be quiet! Straight Power 12 650W',
      slug: 'bequiet-straight-power-12-650w',
      brand: 'be quiet!',
      category: 'PSU' as const,
      description: '650W 80+ Platinum. Whisper-quiet operation. ATX 3.0 ready. Ideal for mid-range builds up to RTX 4070.',
      price: 129.99,
      stock: 48,
      images: ['https://cdn.pcforge.dev/products/straight-power-12.jpg'],
      wattage: 650,
      specs: [
        { key: 'Wattage', value: '650', unit: 'W' },
        { key: 'Efficiency', value: '80+ Platinum' },
        { key: 'Modularity', value: 'Fully Modular' },
        { key: 'ATX Version', value: 'ATX 3.0' },
        { key: 'Warranty', value: '10 years' },
      ],
    },
    // Cooling
    {
      name: 'Noctua NH-D15 CPU Cooler',
      slug: 'noctua-nh-d15',
      brand: 'Noctua',
      category: 'COOLING' as const,
      description: 'Best air cooler ever made. Dual tower, dual 140mm fans. Handles TDPs up to 250W. Fits LGA1700, AM5 and more. Near-silent operation.',
      price: 99.99,
      stock: 38,
      images: ['https://cdn.pcforge.dev/products/nh-d15.jpg'],
      tdp: 250,
      formFactor: 'Air Cooler',
      specs: [
        { key: 'Type', value: 'Dual Tower Air Cooler' },
        { key: 'Fans', value: '2x 140mm NF-A15' },
        { key: 'Max TDP', value: '250', unit: 'W' },
        { key: 'Height', value: '165', unit: 'mm' },
        { key: 'Socket Support', value: 'LGA1700, LGA1200, AM5, AM4' },
        { key: 'Noise Level', value: '24.6', unit: 'dBA' },
      ],
    },
    {
      name: 'NZXT Kraken 360 RGB AIO',
      slug: 'nzxt-kraken-360-rgb',
      brand: 'NZXT',
      category: 'COOLING' as const,
      description: '360mm AIO liquid cooler. 3x120mm fans, customizable LCD pump head display. Handles flagship CPUs with ease.',
      price: 179.99,
      stock: 28,
      images: ['https://cdn.pcforge.dev/products/kraken-360.jpg'],
      tdp: 350,
      formFactor: 'AIO 360mm',
      specs: [
        { key: 'Type', value: 'AIO Liquid Cooler' },
        { key: 'Radiator Size', value: '360mm' },
        { key: 'Fans', value: '3x 120mm Aer RGB' },
        { key: 'Pump Head', value: 'LCD Display' },
        { key: 'Max TDP', value: '350+', unit: 'W' },
        { key: 'Socket Support', value: 'LGA1700, AM5, AM4' },
      ],
    },
    // Cases
    {
      name: 'Fractal Design Torrent ATX',
      slug: 'fractal-design-torrent-atx',
      brand: 'Fractal Design',
      category: 'CASE' as const,
      description: 'Exceptional airflow mid-tower. Massive front intake with 2x180mm fans + 3x140mm top exhaust included. ATX, mATX, ITX support.',
      price: 189.99,
      stock: 32,
      images: ['https://cdn.pcforge.dev/products/torrent.jpg'],
      formFactor: 'Mid Tower',
      specs: [
        { key: 'Form Factor', value: 'Mid Tower' },
        { key: 'MB Support', value: 'ATX, mATX, ITX' },
        { key: 'Included Fans', value: '2x 180mm + 3x 140mm' },
        { key: 'GPU Clearance', value: '461', unit: 'mm' },
        { key: 'CPU Cooler Clearance', value: '188', unit: 'mm' },
        { key: 'Drive Bays', value: '2x 3.5" + 4x 2.5"' },
        { key: 'Front I/O', value: 'USB-C 3.2, 2x USB-A 3.0' },
      ],
    },
    {
      name: 'Lian Li PC-O11 Dynamic EVO',
      slug: 'lian-li-o11-dynamic-evo',
      brand: 'Lian Li',
      category: 'CASE' as const,
      description: 'The most popular case for high-end builds. Dual chamber design, panoramic glass, supports up to E-ATX. Up to 10 fans or 3x360mm radiators.',
      price: 169.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/o11-evo.jpg'],
      formFactor: 'Mid Tower',
      specs: [
        { key: 'Form Factor', value: 'Mid Tower' },
        { key: 'MB Support', value: 'E-ATX, ATX, mATX, ITX' },
        { key: 'Included Fans', value: '0 (fan ready)' },
        { key: 'GPU Clearance', value: '420', unit: 'mm' },
        { key: 'CPU Cooler Clearance', value: '167', unit: 'mm' },
        { key: 'Radiator Support', value: 'Up to 3x 360mm' },
        { key: 'Front I/O', value: 'USB-C 3.2, 4x USB-A 3.0' },
      ],
    },
    {
      name: 'AMD Ryzen 7 7800X3D',
      slug: 'amd-ryzen-7-7800x3d',
      brand: 'AMD',
      category: 'CPU' as const,
      description: 'The ultimate gaming processor. Zen 4 architecture with 3D V-Cache technology for unparalleled gaming performance.',
      price: 399.99,
      stock: 55,
      images: ['https://cdn.pcforge.dev/products/r7-7800x3d.jpg'],
      tdp: 120,
      socket: 'AM5',
      memoryType: 'DDR5',
      isFeatured: true,
      specs: [
        { key: 'Cores', value: '8' },
        { key: 'Threads', value: '16' },
        { key: 'Boost Clock', value: '5.0', unit: 'GHz' },
        { key: 'L3 Cache', value: '96', unit: 'MB' },
        { key: 'TDP', value: '120', unit: 'W' },
        { key: 'Socket', value: 'AM5' },
      ],
    },
    {
      name: 'Intel Core i7-14700K',
      slug: 'intel-core-i7-14700k',
      brand: 'Intel',
      category: 'CPU' as const,
      description: 'High-end performance for gaming and productivity. 20 cores (8P+12E) and speeds up to 5.6 GHz.',
      price: 409.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/i7-14700k.jpg'],
      tdp: 253,
      socket: 'LGA1700',
      specs: [
        { key: 'Cores', value: '20 (8P+12E)' },
        { key: 'Threads', value: '28' },
        { key: 'Boost Clock', value: '5.6', unit: 'GHz' },
        { key: 'L3 Cache', value: '33', unit: 'MB' },
        { key: 'Socket', value: 'LGA1700' },
      ],
    },
    // GPUs
    {
      name: 'NVIDIA GeForce RTX 4080 Super',
      slug: 'nvidia-geforce-rtx-4080-super',
      brand: 'NVIDIA',
      category: 'GPU' as const,
      description: 'Stunning 4K gaming performance. 16GB GDDR6X memory and advanced ray tracing capabilities.',
      price: 999.99,
      stock: 15,
      images: ['https://cdn.pcforge.dev/products/rtx-4080-super.jpg'],
      tdp: 320,
      specs: [
        { key: 'VRAM', value: '16', unit: 'GB GDDR6X' },
        { key: 'CUDA Cores', value: '10240' },
        { key: 'TDP', value: '320', unit: 'W' },
      ],
    },
    {
      name: 'AMD Radeon RX 7800 XT',
      slug: 'amd-radeon-rx-7800-xt',
      brand: 'AMD',
      category: 'GPU' as const,
      description: 'Excellent 1440p gaming performance with 16GB of VRAM and RDNA 3 architecture.',
      price: 499.99,
      stock: 30,
      images: ['https://cdn.pcforge.dev/products/rx-7800-xt.jpg'],
      tdp: 263,
      specs: [
        { key: 'VRAM', value: '16', unit: 'GB GDDR6' },
        { key: 'Stream Processors', value: '3840' },
        { key: 'TDP', value: '263', unit: 'W' },
      ],
    },
    {
      name: 'ASUS TUF Gaming RTX 4070 OC',
      slug: 'asus-tuf-gaming-rtx-4070-oc',
      brand: 'ASUS',
      category: 'GPU' as const,
      description: 'Durable and high-performance RTX 4070 from ASUS TUF line. Great thermal design.',
      price: 649.99,
      stock: 20,
      images: ['https://cdn.pcforge.dev/products/asus-rtx-4070.jpg'],
      tdp: 200,
      specs: [
        { key: 'VRAM', value: '12', unit: 'GB GDDR6X' },
        { key: 'Brand', value: 'ASUS' },
      ],
    },
    // Motherboards
    {
      name: 'ASUS TUF Gaming B650-PLUS WiFi',
      slug: 'asus-tuf-gaming-b650-plus-wifi',
      brand: 'ASUS',
      category: 'MOTHERBOARD' as const,
      description: 'Reliable B650 AM5 motherboard with WiFi. Perfect for Ryzen 7000 and 8000 series.',
      price: 219.99,
      stock: 45,
      images: ['https://cdn.pcforge.dev/products/b650-plus.jpg'],
      socket: 'AM5',
      formFactor: 'ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'B650' },
        { key: 'Socket', value: 'AM5' },
        { key: 'Memory', value: 'DDR5' },
      ],
    },
    {
      name: 'Gigabyte X670 AORUS ELITE AX',
      slug: 'gigabyte-x670-aorus-elite-ax',
      brand: 'Gigabyte',
      category: 'MOTHERBOARD' as const,
      description: 'High-end X670 motherboard for AM5. Superior power delivery and PCIe 5.0 support.',
      price: 289.99,
      stock: 25,
      images: ['https://cdn.pcforge.dev/products/x670-aorus.jpg'],
      socket: 'AM5',
      formFactor: 'ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'X670' },
        { key: 'Socket', value: 'AM5' },
      ],
    },
    {
      name: 'MSI PRO Z790-P WiFi',
      slug: 'msi-pro-z790-p-wifi',
      brand: 'MSI',
      category: 'MOTHERBOARD' as const,
      description: 'Solid Z790 motherboard for Intel LGA1700. Supports DDR5 and includes WiFi.',
      price: 239.99,
      stock: 35,
      images: ['https://cdn.pcforge.dev/products/msi-z790-p.jpg'],
      socket: 'LGA1700',
      formFactor: 'ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'Z790' },
        { key: 'Socket', value: 'LGA1700' },
      ],
    },
    // RAM
    {
      name: 'Corsair Vengeance RGB 32GB DDR5-6000',
      slug: 'corsair-vengeance-rgb-32gb-ddr5-6000',
      brand: 'Corsair',
      category: 'RAM' as const,
      description: 'High-performance DDR5 memory with vibrant RGB lighting. Optimized for Intel and AMD.',
      price: 139.99,
      stock: 50,
      images: ['https://cdn.pcforge.dev/products/corsair-ddr5-rgb.jpg'],
      memoryType: 'DDR5',
      specs: [
        { key: 'Speed', value: '6000', unit: 'MHz' },
        { key: 'Capacity', value: '32GB (2x16GB)' },
      ],
    },
    {
      name: 'Teamgroup T-Force Delta RGB 32GB DDR5',
      slug: 'teamgroup-t-force-delta-rgb-32gb-ddr5',
      brand: 'Teamgroup',
      category: 'RAM' as const,
      description: 'Stylish DDR5 memory with 120-degree ultra-wide lighting. Great performance and aesthetics.',
      price: 119.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/teamgroup-ddr5.jpg'],
      memoryType: 'DDR5',
      specs: [
        { key: 'Speed', value: '6000', unit: 'MHz' },
        { key: 'Capacity', value: '32GB' },
      ],
    },
    // Storage
    {
      name: 'Crucial T700 2TB PCIe 5.0 NVMe',
      slug: 'crucial-t700-2tb-pcie-5-0',
      brand: 'Crucial',
      category: 'STORAGE' as const,
      description: 'Blazing fast PCIe 5.0 performance. Up to 12,400MB/s reads. The future of storage.',
      price: 279.99,
      stock: 15,
      images: ['https://cdn.pcforge.dev/products/crucial-t700.jpg'],
      specs: [
        { key: 'Interface', value: 'PCIe 5.0 x4' },
        { key: 'Read Speed', value: '12400', unit: 'MB/s' },
      ],
    },
    {
      name: 'Samsung 870 EVO 1TB SATA',
      slug: 'samsung-870-evo-1tb-sata',
      brand: 'Samsung',
      category: 'STORAGE' as const,
      description: 'Reliable SATA SSD for mass storage or older systems. Proven performance and durability.',
      price: 99.99,
      stock: 60,
      images: ['https://cdn.pcforge.dev/products/samsung-870-evo.jpg'],
      specs: [
        { key: 'Interface', value: 'SATA III' },
        { key: 'Capacity', value: '1TB' },
      ],
    },
    {
      name: 'WD Blue 2TB HDD 7200RPM',
      slug: 'wd-blue-2tb-hdd-7200rpm',
      brand: 'Western Digital',
      category: 'STORAGE' as const,
      description: 'High-capacity mechanical hard drive for documents, photos, and large files.',
      price: 59.99,
      stock: 100,
      images: ['https://cdn.pcforge.dev/products/wd-blue-2tb.jpg'],
      specs: [
        { key: 'Interface', value: 'SATA III' },
        { key: 'Speed', value: '7200', unit: 'RPM' },
      ],
    },
    {
      name: 'Seagate IronWolf 8TB NAS HDD',
      slug: 'seagate-ironwolf-8tb-nas-hdd',
      brand: 'Seagate',
      category: 'STORAGE' as const,
      description: 'Durable HDD designed for 24/7 NAS workloads. AgileArray technology for optimal reliability.',
      price: 199.99,
      stock: 20,
      images: ['https://cdn.pcforge.dev/products/ironwolf-8tb.jpg'],
      specs: [
        { key: 'Capacity', value: '8TB' },
        { key: 'Optimization', value: 'NAS' },
      ],
    },
    {
      name: 'Kingston NV2 1TB NVMe',
      slug: 'kingston-nv2-1tb-nvme',
      brand: 'Kingston',
      category: 'STORAGE' as const,
      description: 'Budget-friendly Gen 4x4 NVMe SSD. Great for entry-level builds.',
      price: 64.99,
      stock: 80,
      images: ['https://cdn.pcforge.dev/products/kingston-nv2.jpg'],
      specs: [
        { key: 'Interface', value: 'PCIe 4.0 x4' },
        { key: 'Capacity', value: '1TB' },
      ],
    },
    {
      name: 'Samsung 980 Pro 1TB NVMe',
      slug: 'samsung-980-pro-1tb-nvme',
      brand: 'Samsung',
      category: 'STORAGE' as const,
      description: 'High-performance PCIe 4.0 NVMe SSD. Reliability you can trust from Samsung.',
      price: 109.99,
      stock: 50,
      images: ['https://cdn.pcforge.dev/products/980-pro-1tb.jpg'],
      specs: [
        { key: 'Interface', value: 'PCIe 4.0 x4' },
        { key: 'Capacity', value: '1TB' },
      ],
    },
    {
      name: 'Crucial MX500 1TB SATA SSD',
      slug: 'crucial-mx500-1tb-sata-ssd',
      brand: 'Crucial',
      category: 'STORAGE' as const,
      description: 'Classic SATA SSD with excellent performance and value. Great for secondary storage.',
      price: 84.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/mx500-1tb.jpg'],
      specs: [
        { key: 'Interface', value: 'SATA III' },
        { key: 'Form Factor', value: '2.5"' },
      ],
    },
    {
      name: 'Seagate BarraCuda 2TB HDD',
      slug: 'seagate-barracuda-2tb-hdd',
      brand: 'Seagate',
      category: 'STORAGE' as const,
      description: 'Versatile HDD for all your PC needs. Reliable and cost-effective.',
      price: 54.99,
      stock: 90,
      images: ['https://cdn.pcforge.dev/products/barracuda-2tb.jpg'],
      specs: [
        { key: 'Speed', value: '7200', unit: 'RPM' },
        { key: 'Capacity', value: '2TB' },
      ],
    },
    {
      name: 'Gigabyte Z790 AORUS MASTER',
      slug: 'gigabyte-z790-aorus-master',
      brand: 'Gigabyte',
      category: 'MOTHERBOARD' as const,
      description: 'Ultimate Z790 motherboard with massive thermal design and PCIe 5.0 support.',
      price: 499.99,
      stock: 10,
      images: ['https://cdn.pcforge.dev/products/z790-aorus-master.jpg'],
      socket: 'LGA1700',
      formFactor: 'E-ATX',
      memoryType: 'DDR5',
      specs: [
        { key: 'Chipset', value: 'Z790' },
        { key: 'Memory', value: 'DDR5' },
      ],
    },
    // Cases
    {
      name: 'NZXT H5 Flow RGB',
      slug: 'nzxt-h5-flow-rgb',
      brand: 'NZXT',
      category: 'CASE' as const,
      description: 'Compact mid-tower case with high airflow and vibrant RGB lighting.',
      price: 119.99,
      stock: 45,
      images: ['https://cdn.pcforge.dev/products/nzxt-h5-flow.jpg'],
      formFactor: 'Mid Tower',
      specs: [
        { key: 'Form Factor', value: 'Mid Tower' },
        { key: 'MB Support', value: 'ATX, Micro-ATX, Mini-ITX' },
        { key: 'Fans Included', value: '2 x 140mm RGB' },
      ],
    },
    {
      name: 'Corsair 4000D Airflow',
      slug: 'corsair-4000d-airflow',
      brand: 'Corsair',
      category: 'CASE' as const,
      description: 'The standard for airflow cases. Simple, clean, and extremely effective thermal performance.',
      price: 104.99,
      stock: 60,
      images: ['https://cdn.pcforge.dev/products/corsair-4000d.jpg'],
      formFactor: 'Mid Tower',
      specs: [
        { key: 'Form Factor', value: 'Mid Tower' },
        { key: 'Color', value: 'Black/White' },
      ],
    },
    {
      name: 'Hyte Y60 Panoramic',
      slug: 'hyte-y60-panoramic',
      brand: 'Hyte',
      category: 'CASE' as const,
      description: 'Stunning 3-piece panoramic glass design for a complete view of your build.',
      price: 199.99,
      stock: 20,
      images: ['https://cdn.pcforge.dev/products/hyte-y60.jpg'],
      formFactor: 'Mid Tower',
      specs: [
        { key: 'Design', value: 'Panoramic Glass' },
        { key: 'GPU Mount', value: 'Vertical Only' },
      ],
    },
    // PSUs
    {
      name: 'EVGA SuperNOVA 850 GT',
      slug: 'evga-supernova-850-gt',
      brand: 'EVGA',
      category: 'PSU' as const,
      description: '850W 80+ Gold fully modular power supply. Reliable performance with a compact design.',
      price: 139.99,
      stock: 30,
      images: ['https://cdn.pcforge.dev/products/evga-850gt.jpg'],
      wattage: 850,
      specs: [
        { key: 'Wattage', value: '850W' },
        { key: 'Efficiency', value: '80+ Gold' },
      ],
    },
    {
      name: 'Thermaltake Toughpower GF3 1000W',
      slug: 'thermaltake-toughpower-gf3-1000w',
      brand: 'Thermaltake',
      category: 'PSU' as const,
      description: 'ATX 3.0 ready PSU with native PCIe 5.0 connector for high-end GPUs like RTX 4090.',
      price: 179.99,
      stock: 25,
      images: ['https://cdn.pcforge.dev/products/tt-gf3-1000w.jpg'],
      wattage: 1000,
      specs: [
        { key: 'ATX Standard', value: 'ATX 3.0' },
        { key: 'PCIe 5.0', value: 'Yes' },
      ],
    },
    {
      name: 'Cooler Master MWE Gold 750 V2',
      slug: 'cooler-master-mwe-gold-750-v2',
      brand: 'Cooler Master',
      category: 'PSU' as const,
      description: 'Efficient and quiet 750W 80+ Gold power supply. Great for mid-range builds.',
      price: 99.99,
      stock: 50,
      images: ['https://cdn.pcforge.dev/products/cm-mwe-750.jpg'],
      wattage: 750,
      specs: [
        { key: 'Wattage', value: '750W' },
        { key: 'Efficiency', value: '80+ Gold' },
      ],
    },
    // Cooling
    {
      name: 'Corsair iCUE H150i Elite LCD XT',
      slug: 'corsair-icue-h150i-elite-lcd-xt',
      brand: 'Corsair',
      category: 'COOLING' as const,
      description: '360mm AIO liquid cooler with a built-in LCD screen for system monitoring or custom GIFs.',
      price: 289.99,
      stock: 15,
      images: ['https://cdn.pcforge.dev/products/h150i-lcd.jpg'],
      formFactor: '360mm AIO',
      specs: [
        { key: 'Type', value: 'Liquid Cooler' },
        { key: 'Radiator', value: '360mm' },
        { key: 'LCD Screen', value: 'Yes' },
      ],
    },
    {
      name: 'Cooler Master Hyper 212 Halo',
      slug: 'cooler-master-hyper-212-halo',
      brand: 'Cooler Master',
      category: 'COOLING' as const,
      description: 'The legend returns with a new Halo fan. Best-in-class budget air cooling with RGB.',
      price: 49.99,
      stock: 80,
      images: ['https://cdn.pcforge.dev/products/hyper-212-halo.jpg'],
      formFactor: 'Air Cooler',
      specs: [
        { key: 'Type', value: 'Air Cooler' },
        { key: 'RGB', value: 'Yes' },
      ],
    },
    {
      name: 'DeepCool AK620 Digital',
      slug: 'deepcool-ak620-digital',
      brand: 'DeepCool',
      category: 'COOLING' as const,
      description: 'High-performance dual tower air cooler with a digital status screen on top.',
      price: 79.99,
      stock: 35,
      images: ['https://cdn.pcforge.dev/products/ak620-digital.jpg'],
      formFactor: 'Air Cooler',
      specs: [
        { key: 'Type', value: 'Air Cooler' },
        { key: 'Display', value: 'Digital CPU Temp' },
      ],
    },
    {
      name: 'ARCTIC Liquid Freezer III 360',
      slug: 'arctic-liquid-freezer-iii-360',
      brand: 'ARCTIC',
      category: 'COOLING' as const,
      description: 'Top-tier cooling performance at an unbeatable price. Includes VRM fan for extra stability.',
      price: 119.99,
      stock: 40,
      images: ['https://cdn.pcforge.dev/products/arctic-lf3.jpg'],
      formFactor: '360mm AIO',
      specs: [
        { key: 'Type', value: 'Liquid Cooler' },
        { key: 'VRM Fan', value: 'Included' },
      ],
    }
  ]

  console.log(`📦 Creating ${products.length} products...`)

  for (const product of products) {
    const { specs, ...productData } = product
    await prisma.product.upsert({
      where: { slug: productData.slug },
      update: {},
      create: {
        ...productData,
        specs: { create: specs },
      },
    })
  }

  console.log('✅ Seed completed successfully!')
  console.log(`👤 Admin: admin@pcforge.dev / Admin123!`)
  console.log(`👤 Customer: juan@example.com / Customer123!`)
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
